-- Person A: Has partyId, ready for PartyAssets creation
-- All assistance_types covered across FARDTJANST and RIKSFARDTJANST

-- FARDTJANST group (13 rows covering: type, transportMode, additionalAids, mobilityAids, winterService, notes, permit-type)
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (1,  '199001011234', 'Arbetsresor',                    '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (2,  '199001011234', 'Buss',                           '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (3,  '199001011234', 'Specialfordon',                  '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (4,  '199001011234', 'Bil',                            '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (5,  '199001011234', 'Baksäte',                        '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (6,  '199001011234', 'Framsäte',                       '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (7,  '199001011234', 'Ensamåkning',                    '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (8,  '199001011234', 'Hämta/Lämna bostaden',           '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (9,  '199001011234', 'Färdtjänst med ledsagare',       '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (10, '199001011234', 'Färdtjänst utan ledsagare',      '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (11, '199001011234', 'Rollator',                       '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (12, '199001011234', 'Kryckor/käpp',                   '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (13, '199001011234', 'Rullstol',                       '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (14, '199001011234', 'Vinterfärdtjänst',               '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (15, '199001011234', 'Anslutningsresa m specialfordon','2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (16, '199001011234', 'Enstaka resa',                   '2026-01-01', '2027-01-01', 'FARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');

-- RIKSFARDTJANST group (11 rows covering remaining assistance_types)
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (17, '199001011234', 'Generellt tillstånd',             '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (18, '199001011234', 'Privatresor',                    '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (19, '199001011234', 'Flyg',                           '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (20, '199001011234', 'Tåg',                            '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (21, '199001011234', 'Riksfärdtjänst med ledsagare',   '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (22, '199001011234', 'Riksfärdtjänst utan ledsagare',  '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (23, '199001011234', 'Stavar',                         '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (24, '199001011234', 'Ledarhund',                      '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (25, '199001011234', 'Vagn',                           '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (26, '199001011234', 'Syrgas',                         '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (27, '199001011234', 'Elmoped',                        '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
INSERT INTO procapita_raw (id, personal_number, assistance_type, start_date, end_date, permit_group, party_id, status) VALUES (28, '199001011234', 'Elrullstol',                     '2026-03-01', NULL, 'RIKSFARDTJANST', 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'PARTY_ID_FETCHED');
