#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
  security:
    oauth2:
      client:
        registration:
          party:
            provider: party
            client-id: test
            client-secret: test
            authorization-grant-type: client_credentials
          partyassets:
            provider: partyassets
            client-id: test
            client-secret: test
            authorization-grant-type: client_credentials
        provider:
          party:
            token-uri: http://localhost:9999/token
          partyassets:
            token-uri: http://localhost:9999/token
integration:
  party:
    base-url: http://localhost:9999
  partyassets:
    base-url: http://localhost:9999
